name: sapa_core
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Core
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.2.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  flutter_bloc: ^8.1.3
  alice: ^0.3.1
  equatable: ^2.0.5
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

