name: sapa_sekolah_wali
description: A new Flutter project.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Components
  sapa_component:
    path: ../../packages/sapa_component/
  # Core
  sapa_core:
    path: ../../packages/sapa_core/

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:  
  build_runner: 
  flutter_gen_runner:
  flutter_lints: ^2.0.0

dependency_overrides:

flutter_gen:
  integrations:
    flutter_svg: true
    
flutter:

  uses-material-design: true

  assets:
    - assets/images/
